dialplan/asterisk/extensions_lib_paging.conf
This allow a digium d70 to work as intercom.
It needs also a provisionning update
=> digium intercom support

dialplan/asterisk/extensions_lib_user.conf
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1707
=> add user NAME to XIVO_USER_FWD event

dialplan/asterisk/extensions_lib_user.conf
Depends-on: https://github.com/wazo-platform/wazo-agid/pull/30
=> use already merged variable instead of two separate

dialplan/asterisk/extensions_lib_user.conf
Depends-on: https://github.com/wazo-platform/xivo-config/pull/14
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1710
=> Pull request for WAZO-1710-WAZO-1709-fix-wrong-requested-internal

dialplan/asterisk/extensions_lib_did.conf
Depends-on: https://github.com/wazo-platform/wazo-agid/pull/31
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1738
=> incall: play greeting sound

dialplan/asterisk/extensions_lib_agents.conf, dialplan/asterisk/extensions_lib_originate.conf, dialplan/asterisk/extensions_lib_outcall.conf, dialplan/asterisk/extensions_lib_pre_dial.conf, dialplan/asterisk/extensions_lib_user.conf
Depends-On: https://github.com/wazo-platform/wazo-agid/pull/58
=> WAZO-2176 pre dial handlers

dialplan/asterisk/extensions_lib_group.conf, dialplan/asterisk/extensions_lib_outcall.conf, dialplan/asterisk/extensions_lib_queue.conf, dialplan/asterisk/extensions_lib_user.conf
Depends-On: https://github.com/wazo-platform/wazo-agid/pull/63
=> Wazo 2257 recording queues groups

dialplan/asterisk/extensions_lib_switchboard.conf
Why:
* Set the switchboard fallback destination
=> Pull request for WAZO-2422-switchboard-fallback-noanswer

dialplan/asterisk/extensions_lib_agents.conf
this is now done by wazo-agentd
Depends-On: https://github.com/wazo-platform/wazo-agentd/pull/54
=> agent login: remove BLF handling

sbin/xivo-manage-slave-services
Depends-on: https://github.com/wazo-platform/wazo-agentd-client/pull/13
Depends-on: https://github.com/wazo-platform/wazo-agentd-cli/pull/12
=> set custom timeout on relog all command

dialplan/asterisk/extensions_lib_features.conf
Depends-On: https://github.com/wazo-platform/wazo-agid/pull/82
=> extenfeatures: add meetingjoin

sbin/xivo-create-config, templates/dhcp/etc/dhcp/dhcpd.conf, tests/test_xivo_create_config.py
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/222
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/243
=> [WAZO-1760] Add provisioning server URL to DHCP configuration

dialplan/asterisk/extensions_lib_user.conf
https://wazo-dev.atlassian.net/browse/WAZO-3292
=> Emitting custom CEL from usersharedlines context

dialplan/asterisk/extensions_lib_user.conf
https://wazo-dev.atlassian.net/browse/WP-1005
=> Updated forward_voicemail routine to allow voicemail redirection from ring group

dialplan/asterisk/extensions_lib_group.conf, dialplan/asterisk/extensions_lib_user.conf
https://wazo-dev.atlassian.net/browse/WP-1395
Depends-On: https://github.com/wazo-platform/wazo-agid/pull/149
=> Wp 1395 linear group moh

dialplan/asterisk/extensions_lib_group.conf, dialplan/asterisk/extensions_lib_user.conf
Depends-on: https://github.com/wazo-platform/wazo-agid/pull/152
=> linear group: refactoring for ring-in-use option support

dialplan/asterisk/extensions_lib_group.conf
Depends-on: https://github.com/wazo-platform/wazo-agid/pull/153
=> extensions_lib_group: added WAZO_CALL_LOG_DESTINATION custom CEL

dialplan/asterisk/extensions_lib_user.conf
Depends-On: https://github.com/wazo-platform/wazo-agid/pull/190
=> blocklist: blocklist screening

dialplan/asterisk/extensions_lib_outcall.conf
Why: it's now done in callerid AGI
=> WP-1746 Remove diversion handling

.pre-commit-config.yaml, pyproject.toml, requirements.txt, tox.ini, zuul.yaml
- **upgrade CI to bookworm**
- **update python library version to bookworm**
=> WAZO-4301-bookworm
