wazo-platform/xivo-config

etc/nginx/locations/https-available/asterisk
Sometimes on webrtc we have some calls who are very long. After some research we find there is an issue with the buffer size on ssl termination  with nginx. This issue is not present with apache, but in fact we don't need to have an ssl termination between asterisk and nginx by default. So just change the configuration to use the asterisk http endpoint instead https fix this issue.
=> Fix issue with some calls are very long

dialplan/asterisk/extensions_lib_vmbox.conf
In this context ARG2 contains options for the Voicemail application. The
possible values are "b" and "u" which are mutually exclusive.
When "b" is used the message indicates that the user is busy.
When "u" is used the message indicates that the user is unavailable.
When none of the above is set the we are invited to leave a message.
So, whats happening here.
FILTER(u,$(ARGS)) will return "u" if ARG2 contains "u" ex: "busy" ==> "u"
The IF will match the "u" and set the XIVO_MAILBOX_OPTIONS to "u"
Since "b" is mutually exclusive with "u" we can safely overrite the previous
value if "b" is set.
=> voicemail: on destination voicemail do not ignore the options

sbin/xivo-manage-slave-services
wazo-auth was restarted to re-generate the tenant tree cache on the slave. The
cache has been removed.
Depends-On: https://github.com/wazo-platform/wazo-auth/pull/71
=> WAZO-1610: manage slave service: stop restart wazo-auth

dialplan/asterisk/extensions_lib_user.conf
Why:
* If a mobile app is registered with a SIP line with uppercase characters
and receives a call, the dialplan stops.
=> mobile: allow uppercase characters in SIP line name

sbin/xivo-manage-slave-services
reason: wazo-agentd is now started without forking by systemd and the
systemd gives back the hand faster than before
=> wait until wazo-agentd HTTP is ready

dialplan/asterisk/extensions_lib_user.conf
Why:
* The pattern is very hard to read and does not bring any value, since
the AGI already checks if the UUID is valid.
=> extensions_lib_user: simplify usersharedlines

sbin/xivo-manage-slave-services
Why:
* wazo-agentd now includes its own wait in systemd service file
Depends-On: https://github.com/wazo-platform/wazo-agentd/pull/20
=> remove wait for wazo-agentd

dialplan/asterisk/extensions_lib_stasis.conf
Why:
* Easier to separate events between applications
* Destruction events are hard to interpret correctly without an explicit
application
=> Pull request for WAZO-1915-adhoc-conference-events

sbin/xivo-manage-slave-services
Why:
* Using xivo services prints a warning that gets emailed by the slave
cron job
=> disable slave: use wazo services

dialplan/asterisk/extensions_lib_user.conf
the only difference between dial_from_group and dial is that dial going to dial
will launch the userevent that triggers the wake mobile. I removed
dial_from_group to avoid duplication
=> [WP-100] Fix wake mobile on group calls using extension members

debian/xivo-config.postinst
asterisk does not have an init file anymore
=> postinst: use systemd instead of invoke-rc.d to stop asterisk

sbin/xivo-master-slave-db-replication
Why:
* master and slave may be in the same subnet
=> HA: exclude DHCP settings from replication

sbin/xivo-update-config
Why:
* Given I have a custom template mail
* When I xivo-update-config
* Then xivo-update-config updates modules in order:
dhcp
mail
system
mail
Expected: it updates modules in order
dhcp
mail
system
Depending on the order of the output of find (depending on the last
update of the directories), we can have:
LIST1=dhcp
mail
system
LIST2=mail
LIST=dhcp
mail
system mail
This happens because the two \n-separated lists are joined with a space.
=> fix module configuration order

dialplan/asterisk/extensions_lib_conference.conf
this prefix will be used to distinguish between configured conference rooms and
dynamic ones created by pagings
=> WAZO-976 conferences: add a prefix to conference ID

dialplan/asterisk/extensions_lib_user.conf
ARG2 can now contain the ringtime as well as a MOH UUID, positions are important
here. If the ringtime is undefined ARG2 SHOULD be ";moh_uuid"
the AGI incoming_user_set_features is then responsible for finding the MOH based
on the UUID and add the "m" option for the "Dial" application.
=> user: make ARG2 of user more dynamic

dialplan/asterisk/extensions_lib_user.conf
changes in the AGI will now add the "Local/<aor>@wait-for-registration"
interface to the dial application. The only missing part is to actually send the
event that will trigger the phone to wake up.
=> usersharedlines: send the mobile push

sbin/xivo-manage-slave-services
`wazo-service status all` returns 0 when services are already started
=> manage-slave-services: do not start services when already started

dialplan/asterisk/extensions_lib_meeting.conf
changes in the AGI will now add the "Local/<aor>@wait-for-registration"
interface to the dial application. The only missing part is to actually send the
event that will trigger the phone to wake up.
Why:
* WAZO_DST_UUID is not set when calling from a group
=> Pull request for WAZO-2518-meetings

dialplan/asterisk/extensions_lib_meeting.conf
guests have all the required variables set on the SIP endpoint
users will call the extension wazo-meeting-<uuid> the meeting_user AGI will
populate all required variables
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/147/files
Depends-On: https://github.com/wazo-platform/wazo-agid/pull/79/files
=> WAZO-2577 meetings: add dialplan for the meeting participants

etc/nginx/locations/https-available/asterisk
Why:
* Asterisk has a default CRLF keep-alive of 90 seconds.
* In some scenarios (meetings), the Websocket is silent (one participant
muted), except for the keep-alive.
* This causes a race-condition between nginx and asterisk, where the WS
has 1:2 chances to be disconnected every 90 seconds.
=> WAZO-2744 Asterisk WS reverse proxy: increase read timeout

dialplan/asterisk/extensions_lib_user.conf
**Why:**
* We need to add an event which will contain all the missing information/fields within the generated call log; when the phone is unreachable,
* We also need to assign a `tenant_uuid` to the logs of missed calls when `caller` phone is unavailable/unreachable.
=> CELGenUserEvent: Add destination_user_uuid to extra

dialplan/asterisk/extensions_lib_pre_dial.conf
https://wazo-dev.atlassian.net/browse/WAZO-2854
the agid handler call is changed to `ignore_b_option` which just ignores any custom usage of the `b` option while logging a warning. 
Depends-On: https://github.com/wazo-platform/wazo-agid/pull/106
=> WAZO-2854: convert_pre_dial_handler deprecated

etc/xivo/asterisk/xivo_in_callerid.conf
https://wazo-dev.atlassian.net/browse/WP-866
* Added a configuration block to interpret french caller id number by stripping international prefix(assuming wazo stack is in french dialplan zone)
=> WP-866 caller id mapping for french local with international prefix

dialplan/asterisk/extensions_lib_features.conf, dialplan/asterisk/extensions_lib_user.conf
If no password for the voicemail, the VoiceMail app is restarted again
If password provided, the VoiceMailMain app is allowed to start.
https://wiki.asterisk.org/wiki/display/AST/Application_VoiceMail
Linked with https://github.com/wazo-platform/wazo-agid/pull/115
=> Disable star key on vm messages checking

requirements.txt, sbin/xivo-create-config, tests/test_xivo_create_config.py
Fix bug in xivo-create-config where `network_interfaces` field in `dhcp` table is expected to be a space-separated string, but data is actually saved by confd as comma-separated.
=> Fix dhcp configuration parsing

dialplan/asterisk/extensions_lib_features.conf
The Pickup application does not work well with Stasis applications. Adding some dialplan around this application allows us to do specific routing before doing the Pickup.
In this case we are going to try to pickup the any dial_mobile that have been started on a AOR matching the PICKUPMARK we are picking up from.
Depends-On: https://github.com/wazo-platform/wazo-calld/pull/296
=> pickup: add a wazo-pickup subroutine

templates/dhcp.restart, templates/mail.restart, templates/system.restart
why: hostname.sh have been removed since systemd. This command do
nothing (silently fail)
=> Pull request for WAZO-3244-use-systemctl

debian/control, debian/xivo-config.dirs
* also remove unused directory. it has been migrated to xivo-certs long
time ago
=> rename xivo-certs to wazo-certs

debian/control
why: was used by old config, but not anymore
=> debian: remove wazo-certs dependency

debian/xivo-config.postinst
why: not used anymore, everything has been migrated to asterisk
packaging
=> Pull request for WAZO-3599-remove-asterisk-fix

dialplan/asterisk/extensions_lib_features.conf
why: this rename was missing from previous PR
=> dialplan: rename XIVO_ENABLE{FWD} to WAZO_ENABLE{FWD}

debian/xivo-config.maintscript, etc/xivo/datastorage.conf
why: was previously used by the old webi (<18.03)
=> remove unused DB credentials

debian/xivo-config.cron.d, sbin/xivo-create-config, sbin/xivo-read-config, tests/test_xivo_create_config.py
why: this script exit 0 if MAX_CALL_DURATION is unset and since 18.03
it's impossible to set this value. The script has been removed too
why: this logic is unusuable since 18.03 and now cause confusion
=> Pull request for WAZO-3659-cleanup-maintenance

dialplan/asterisk/extensions_lib_group.conf
Depends-On: https://github.com/wazo-platform/wazo-agid/pull/174
=> group-linear@group: reset interface variables after use

dialplan/asterisk/extensions_lib_context.conf, dialplan/asterisk/extensions_lib_user.conf
An incoming call does not have a WAZO_USERID (caller) since it comes from external.
=> simultcalls: handle incoming call case

dialplan/asterisk/extensions_lib_outcall.conf
Why:
* Operators expect Diversion header to contain a DID owned by the PBX
sending the header
=> dialplan outcall: allow setting external Diversion SIP header

etc/security/limits.d/asterisk.conf
why: this limit is already set in asterisk.service file
To validate this file has no impact:
`cat /proc/<pid asterisk>/limits`
=> remove unused limits.d/asterisk.conf

dialplan/asterisk/extensions_lib_conference.conf, dialplan/asterisk/extensions_lib_group.conf, dialplan/asterisk/extensions_lib_queue.conf
In the case of incalls to (queue, conference, group), there is no caller user ID and it is not possible to know the final destination until someone answers. Also, depending on the destination, it is only not possible to count because there are multiple users.
=> Do not count calls if WAZO_USERID is missing

dialplan/asterisk/extensions_lib_recording.conf
wazo-record-beep is a subroutine that will append to a recording and playback a sound file.
wazo-record-listening-channel is there to have a call to record.
These subroutines should be used by an originate looking like this
self._ari.channels.originate(
endpoint='Local/s@wazo-record-listening-channel',
context='wazo-record-beep',
extension='s',
priority='1',
variables={'variables': {'WAZO_MIXMONITOR_FILENAME': filename}},
)
=> recording: add subroutine to record beep

dialplan/asterisk/extensions_lib_group.conf
Why: if the group is not linear the check got skipped so the calls went through
=> group: check for max calls before check for linear group

dialplan/asterisk/extensions_lib_recording.conf
=> [WAZO-4032] lib_recording: remove mixmonitor options in beep playback

dialplan/asterisk/extensions_lib_outcall.conf
Why: `tel:number` is not supported by most carriers
=> [WP-1745] extensions_lib_outcall: use number@host format for PAI header

templates/nginx/etc/nginx/sites-available/wazo-provd
why: $domain value was used by a regex captured group long time ago ...
Now the value is a plain "$domain" string which will never match a
valid domain
The standard syntax to use to have a catch-all is "_"
=> WAZO-4174-remove-server-name
